name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.7.3+304

environment:
  sdk: ">=3.2.0-0 <4.0.0"

dependencies:
  android_play_install_referrer: ^0.4.0
  cached_network_image: 3.4.1
  confetti: 0.8.0

  # CONTACTS PLUGIN MIGRATION - IMPORTANT
  # Replaced contacts_service with flutter_contacts due to compilation issues
  #
  # ISSUE: contacts_service 0.6.3 uses deprecated Flutter Android embedding v1 APIs
  # - Specifically: PluginRegistry.Registrar class which was removed in newer Flutter versions
  # - Error: "cannot find symbol import io.flutter.plugin.common.PluginRegistry.Registrar"
  # - This breaks compilation with Flutter 3.x and Android API 35
  #
  # SOLUTION: flutter_contacts is a modern alternative that:
  # - Uses Flutter Android embedding v2 (current standard)
  # - Actively maintained and supports latest Flutter versions
  # - Compatible with Android API 35 and modern Android development
  # - Provides similar contact management functionality
  #
  # CODE MIGRATION REQUIRED:
  # Old: import 'package:contacts_service/contacts_service.dart';
  #      Iterable<Contact> contacts = await ContactsService.getContacts();
  # New: import 'package:flutter_contacts/flutter_contacts.dart';
  #      if (await FlutterContacts.requestPermission()) {
  #        List<Contact> contacts = await FlutterContacts.getContacts();
  #      }
  flutter_contacts: ^1.1.9
  # contacts_service: 0.6.3  # DEPRECATED - Causes PluginRegistry.Registrar compilation errors

  core:
    path: ../core
  auto_route: 10.1.0+1
  blitzllama_flutter: 0.8.0
  country_code_picker: 3.3.0
  device_info_plus: 11.5.0
  file_picker: 10.2.1
  flutter_typeahead: 5.2.0
  # for FirebaseAnalytics (~> 9.2.0)
  # needed for fixing dependency issue in rudder firebase pod due to firebase_analytics
  firebase_core: 4.1.1
  # for FirebaseAnalytics (~> 9.4.0)
  # firebase_core: 1.21.1
  firebase_core_platform_interface: 6.0.1
  firebase_crashlytics: 5.0.0
  firebase_analytics: 12.0.0
  firebase_messaging: 16.0.2
  visibility_detector: 0.4.0+2
  firebase_remote_config: 6.0.0
  local_auth: 2.3.0
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  flutter_downloader: 1.12.0
  flutter_local_notifications: 19.4.2
  flutter_pdfview: 1.4.3
  flutter_spinkit: 5.2.1
  flutter_svg: 2.2.0
  flutter_swiper_null_safety: 1.0.2
  flutter_widget_from_html: 0.17.0
  freshchat_sdk: 0.10.26
  get: 4.7.2
  mixpanel_flutter: 2.4.4
  in_app_update: 4.2.3
  lottie: 3.3.1
  overflow_view: 0.5.0
  otp_autofill: 4.1.0
  permission_handler: 12.0.1
  readmore: 3.0.0
  # razorpay_flutter: 1.4.0
  shared_preferences: 2.5.3
  shimmer: 3.0.0
  story_view: 0.16.6

  # Error: "cannot find symbol import io.flutter.plugin.common.PluginRegistry.Registrar"
  # Trying newer version that hopefully supports Android embedding v2
  # uni_links: 0.5.1
  app_links: 6.4.0

  url_launcher: 6.3.2
  web_socket_channel: 3.0.3
  webview_flutter: 4.13.0
  whatsapp_unilink: 2.1.0
  # youtube_plyr_iframe: ^2.0.7
  youtube_player_iframe: 5.2.2
  smooth_page_indicator: 1.2.1
  dropdown_button2: 2.3.9
  flutter_keyboard_visibility: 6.0.0
  fl_chart: 1.0.0
  marquee: 2.2.3

  # Fix for send_to_background crash issue with Flutter 3.x
  # ISSUE: send_to_background package crashes with "An operation is not implemented: Not yet implemented"
  # - This error occurs when trying to send the app to background on certain devices/OS versions
  # - The published version on pub.dev has unresolved implementation issues
  #
  # SOLUTION: Using forked version with crash fix
  # - Fork contains proper implementation for the missing functionality
  # - Resolves "Not yet implemented" exception during background operations
  # - Compatible with latest Flutter versions and Android embedding v2
  #
  # Original issue with move_to_background:
  # Version 1.0.2 uses deprecated Android embedding v1 APIs (PluginRegistry.Registrar)
  # Error: "cannot find symbol import io.flutter.plugin.common.PluginRegistry.Registrar"
  # move_to_background: ^1.0.3
  #
  # NOTE: Using HEAD to always fetch the latest commit from master branch
  # This ensures we get the most recent fixes without caching issues
  send_to_background:
    git:
      url: https://github.com/vikramkumarofficial/send_to_background.git
      ref: HEAD

  app_tracking_transparency: 2.0.6+1
  path_provider: 2.1.5
  showcaseview: 4.0.1
  simple_animations: 5.2.0
  flutter_inappwebview: 6.1.5
  # flutter_inappwebview: ^5.7.2+3
  scrollable_positioned_list: 0.3.8

  # Fix for image_gallery_saver JVM target compatibility issue
  # Plugin has JVM target mismatch (1.8 vs 17) causing Kotlin compilation errors
  # Forcing newer version that supports consistent JVM targets
  ## https://github.com/hui-z/image_gallery_saver/issues/328
  # image_gallery_saver: ^2.0.3
  flutter_image_gallery_saver: ^0.0.2

  responsive_framework: 1.5.1
  share_plus: 12.0.1
  in_app_review: 2.0.10
  collection: 1.19.1
  carousel_slider: 5.1.1
  new_version_plus: 0.1.1
  package_info_plus: 8.3.0

  month_picker_dialog: 6.4.1
  image_picker: 1.1.2
  screenshot: 3.0.0
  pdf: 3.11.3
  image: 4.5.4

  # Fix for move_to_background compilation error with Flutter 3.x
  # Version 1.0.2 uses deprecated Android embedding v1 APIs (PluginRegistry.Registrar)
  # Error: "cannot find symbol import io.flutter.plugin.common.PluginRegistry.Registrar"
  # Trying newer version that hopefully supports Android embedding v2
  # open_file_plus: 3.4.1+1
  open_file_plus:
    git:
      url: https://github.com/vikramkumarofficial/open_file_plus.git

  image_cropper: 9.1.0
  flutter_markdown: 0.7.7+1
  flutter_staggered_grid_view: 0.7.0

dev_dependencies:
  flutter_launcher_icons: 0.14.4
  build_runner: 2.5.4
  auto_route_generator: 10.2.3
  flutter_test:
    sdk: flutter

dependency_overrides:
  # Fix for fluttertoast compilation error with Flutter 3.x
  # Version 8.2.8 uses deprecated Android embedding v1 APIs (Registrar, FlutterMain)
  # Forcing newer version that supports Android embedding v2
  fluttertoast: 8.2.12

flutter_icons:
  ios: true
  android: false
  image_path_ios: "assets/images/launcher/app_icon.png"
  image_path_android: "assets/images/launcher/app_icon.png"
  adaptive_icon_background: "#6725F4"
  # adaptive_icon_foreground: "assets/images/launcher/app_icon.png"
  remove_alpha_ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/launcher/
    - assets/images/
    - assets/images/tabs/
    - assets/images/onboarding/
    - assets/images/home/
    - assets/images/clients/
    - assets/images/clients/profile/
    - assets/images/clients/goal/
    - assets/images/store/
    - assets/images/store/demat/
    - assets/images/store/sgb/
    - assets/images/store/mf/
    - assets/images/more/
    - assets/images/profile/
    - assets/images/rewards/
    - assets/images/kyc/
    - assets/images/broking/
    - assets/images/sip_book/
    - assets/html/
    - assets/data/
    - assets/images/guide/
    - assets/images/commons/
    - assets/images/lock/
    - assets/images/proposals/
    - assets/images/wealth_academy/
    - assets/images/my_team/
    - assets/images/insurance/
    - assets/images/business_report/
    - assets/images/my_business/
    - assets/images/ticob/
    - assets/images/newsletters/
    - assets/images/calculator/
    - assets/images/ai/
    - assets/images/birthday/
    - assets/images/wealthcase/

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/LatoSemibold.ttf
          weight: 600
        - asset: assets/fonts/Lato-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
